apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  creationTimestamp: null
  name: httpbin basic auth
spec:
  CORS:
    allowed_headers:
    - Origin
    - Accept
    - Content-Type
    - X-Requested-With
    - Authorization
    allowed_methods:
    - GET
    - POST
    - HEAD
    allowed_origins:
    - '*'
    max_age: 24
  active: true
  api_id: ca7ad124687f45de549a834d7c90dd2c
  auth:
    auth_header_name: Authorization
    signature:
      algorithm: ""
      allowed_clock_skew: 0
      error_code: 0
      error_message: ""
      header: ""
      secret: ""
  auth_configs:
    authToken:
      auth_header_name: Authorization
      signature:
        algorithm: ""
        allowed_clock_skew: 0
        error_code: 0
        error_message: ""
        header: ""
        secret: ""
    basic:
      auth_header_name: Authorization
      signature:
        algorithm: ""
        allowed_clock_skew: 0
        error_code: 0
        error_message: ""
        header: ""
        secret: ""
    coprocess:
      auth_header_name: Authorization
      signature:
        algorithm: ""
        allowed_clock_skew: 0
        error_code: 0
        error_message: ""
        header: ""
        secret: ""
    hmac:
      auth_header_name: Authorization
      signature:
        algorithm: ""
        allowed_clock_skew: 0
        error_code: 0
        error_message: ""
        header: ""
        secret: ""
    jwt:
      auth_header_name: Authorization
      signature:
        algorithm: ""
        allowed_clock_skew: 0
        error_code: 0
        error_message: ""
        header: ""
        secret: ""
    oauth:
      auth_header_name: Authorization
      signature:
        algorithm: ""
        allowed_clock_skew: 0
        error_code: 0
        error_message: ""
        header: ""
        secret: ""
    oidc:
      auth_header_name: Authorization
      signature:
        algorithm: ""
        allowed_clock_skew: 0
        error_code: 0
        error_message: ""
        header: ""
        secret: ""
  cache_options:
    cache_timeout: 60
    enable_cache: true
  config_data:
    k8sName: httpbin basic auth
  custom_middleware:
    auth_check:
      name: ""
      path: ""
    driver: ""
    id_extractor:
      extract_from: ""
      extract_with: ""
      extractor_config: {}
  definition:
    key: x-api-version
    location: header
    strip_path: false
  do_not_track: false
  global_rate_limit:
    per: 0
    rate: 0
  graphql:
    enabled: false
    engine:
      data_sources: []
      field_configs: []
    execution_mode: proxyOnly
    playground:
      enabled: false
      path: ""
    proxy:
      auth_headers: {}
    subgraph:
      sdl: ""
    supergraph: {}
    version: "2"
  id: 6435b6dfe1dc2100011f34d2
  listen_port: 0
  name: httpbin basic auth
  oauth_meta:
    allowed_access_types: []
    allowed_authorize_types: []
  org_id: 6435b667e1dc2100011f34ce
  protocol: ""
  proxy:
    disable_strip_slash: true
    listen_path: /httpbin-basic-auth/
    service_discovery:
      cache_timeout: 0
      data_path: ""
      endpoint_returns_list: false
      parent_data_path: ""
      port_data_path: ""
      query_endpoint: ""
      target_path: ""
      use_discovery_service: false
      use_nested_query: false
      use_target_list: false
    strip_listen_path: true
    target_url: http://httpbin.org/
    transport: {}
  use_basic_auth: true
  version_data:
    default_version: ""
    not_versioned: true
    versions:
      Default:
        extended_paths: {}
        name: Default
        paths: {}
        use_extended_paths: true
status:
  api_id: ""

---
